<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private '.service_locator.uyaF8Pv' shared service.

return $this->privates['.service_locator.uyaF8Pv'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($this->getService, [
    'pokemon' => ['privates', '.errored..service_locator.uyaF8Pv.App\\Entity\\Pokemon', NULL, 'Cannot autowire service ".service_locator.uyaF8Pv": it references class "App\\Entity\\Pokemon" but no such service exists.'],
]);
