<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private '.errored..service_locator.ReXks9R.App\Entity\Soint' shared service.

include_once $this->targetDirs[3].'\\src\\Entity\\Master.php';
include_once $this->targetDirs[3].'\\src\\Entity\\Soint.php';

return $this->privates['.errored..service_locator.ReXks9R.App\Entity\Soint'] = new \App\Entity\Soint();
