<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private 'debug.argument_resolver.service' shared service.

include_once $this->targetDirs[3].'\\vendor\\symfony\\http-kernel\\Controller\\ArgumentValueResolverInterface.php';
include_once $this->targetDirs[3].'\\vendor\\symfony\\http-kernel\\Controller\\ArgumentResolver\\TraceableValueResolver.php';
include_once $this->targetDirs[3].'\\vendor\\symfony\\http-kernel\\Controller\\ArgumentResolver\\ServiceValueResolver.php';

return $this->privates['debug.argument_resolver.service'] = new \Symfony\Component\HttpKernel\Controller\ArgumentResolver\TraceableValueResolver(new \Symfony\Component\HttpKernel\Controller\ArgumentResolver\ServiceValueResolver(new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($this->getService, [
    'App\\Controller\\BagController::index' => ['privates', '.service_locator.kR1vATl', 'get_ServiceLocator_KR1vATlService.php', true],
    'App\\Controller\\BagController::show' => ['privates', '.service_locator.ReXks9R', 'get_ServiceLocator_ReXks9RService.php', true],
    'App\\Controller\\PokemonController::delete' => ['privates', '.service_locator.uyaF8Pv', 'get_ServiceLocator_UyaF8PvService.php', true],
    'App\\Controller\\PokemonController::edit' => ['privates', '.service_locator.uyaF8Pv', 'get_ServiceLocator_UyaF8PvService.php', true],
    'App\\Controller\\PokemonController::index' => ['privates', '.service_locator.lH9O__v', 'get_ServiceLocator_LH9OVService.php', true],
    'App\\Controller\\PokemonController::show' => ['privates', '.service_locator.uyaF8Pv', 'get_ServiceLocator_UyaF8PvService.php', true],
    'App\\Controller\\SecurityController::login' => ['privates', '.service_locator.EbLunuf', 'get_ServiceLocator_EbLunufService.php', true],
    'App\\Controller\\BagController:index' => ['privates', '.service_locator.kR1vATl', 'get_ServiceLocator_KR1vATlService.php', true],
    'App\\Controller\\BagController:show' => ['privates', '.service_locator.ReXks9R', 'get_ServiceLocator_ReXks9RService.php', true],
    'App\\Controller\\PokemonController:delete' => ['privates', '.service_locator.uyaF8Pv', 'get_ServiceLocator_UyaF8PvService.php', true],
    'App\\Controller\\PokemonController:edit' => ['privates', '.service_locator.uyaF8Pv', 'get_ServiceLocator_UyaF8PvService.php', true],
    'App\\Controller\\PokemonController:index' => ['privates', '.service_locator.lH9O__v', 'get_ServiceLocator_LH9OVService.php', true],
    'App\\Controller\\PokemonController:show' => ['privates', '.service_locator.uyaF8Pv', 'get_ServiceLocator_UyaF8PvService.php', true],
    'App\\Controller\\SecurityController:login' => ['privates', '.service_locator.EbLunuf', 'get_ServiceLocator_EbLunufService.php', true],
])), ($this->privates['debug.stopwatch'] ?? ($this->privates['debug.stopwatch'] = new \Symfony\Component\Stopwatch\Stopwatch(true))));
