<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerF6zW8xT\srcApp_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerF6zW8xT/srcApp_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerF6zW8xT.legacy');

    return;
}

if (!\class_exists(srcApp_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerF6zW8xT\srcApp_KernelDevDebugContainer::class, srcApp_KernelDevDebugContainer::class, false);
}

return new \ContainerF6zW8xT\srcApp_KernelDevDebugContainer([
    'container.build_hash' => 'F6zW8xT',
    'container.build_id' => '7446ceb9',
    'container.build_time' => 1558516180,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerF6zW8xT');
